name: Build & push with Depot

on:
  push:
    branches: [ "main" ]

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push (Depot)
        uses: depot/build-push-action@v1
        with:
          project: 9s8hpzzv0s
          token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
          context: .
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/lets-prep-prototype:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/lets-prep-prototype:sha-${{ github.sha }}